# Generated by Django 2.2 on 2019-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190526_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=70, null=True, unique_for_date='published'),
        ),
    ]
