# Generated by Django 2.2 on 2019-05-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190527_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-published',)},
        ),
    ]
